# name: Trigger TeamCity Build

# on:
#   push:
#     branches:
#       - main

# jobs:
#   trigger-teamcity:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Trigger TeamCity Build
#         env:
#           TEAMCITY_SERVER_URL: ${{ secrets.TEAMCITY_SERVER_URL }}
#           TEAMCITY_API_TOKEN: ${{ secrets.TEAMCITY_API_TOKEN }}
#           TEAMCITY_BUILD_TYPE_ID: ${{ secrets.TEAMCITY_BUILD_TYPE_ID }}
#         run: |
#           curl -X POST \
#           -H "Content-Type: application/json" \
#           -H "Authorization: Bearer $TEAMCITY_API_TOKEN" \
#           "$TEAMCITY_SERVER_URL/app/rest/buildQueue" \
#           -d '{"buildType": {"id": "'$TEAMCITY_BUILD_TYPE_ID'"}}'
