name: Deploy Windows Application Dotnet 4.8

on:
  push:
    branches:
      - main
    paths:
      - "WindowsFormsApp/**" # Trigger only on changes within the WindowsFormsApp folder
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Mono
        run: |
          sudo apt-get update
          sudo apt-get install -y mono-complete

      - name: Restore NuGet packages
        run: nuget restore ./WindowsFormsApp/WindowsFormsApp.sln

      - name: Build the project
        run: |
          msbuild /p:Configuration=Release ./WindowsFormsApp/WindowsFormsApp.csproj
          ls ./WindowsFormsApp/bin

      - name: Install expect
        run: sudo apt-get update && sudo apt-get install -y expect openssh-client

      - name: Create SSH directory and known_hosts file
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Add SSH key to known_hosts
        run: |
          ssh-keyscan -H 54.173.94.91 >> ~/.ssh/known_hosts

      - name: Take Backup
        run: |
          expect -c '
          spawn ssh "${{secrets.EC2_USERNAME}}@${{secrets.EC2_HOST}}
          sleep 3
          expect "${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}'\''s password:"
          sleep 3
          send "${{ secrets.SSH_PASSWORD }}\r"
          sleep 3
          COPY C:\inetpub\wwwroot\WinFormsApp C:\
          interact
          '

      - name: Deploy to AWS EC2
        run: |
          expect -c '
          spawn scp -r -o StrictHostKeyChecking=no ./WindowsFormsApp/bin/Release/ ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/C:/inetpub/wwwroot/WinFormsApp/
          sleep 3
          expect "${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}'\''s password:"
          sleep 3
          send "${{ secrets.SSH_PASSWORD }}\r"
          sleep 3
          interact
          '
